version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    environment:
        - FLASK_ENV=development
        - FLASK_RUN_EXTRA_FILES=templates/*
    links:
    - mongodb
  mongodb:
    image: 'mongo:3.6-xenial'
